name: TagMessages
main: Clarence2810\tagmessages\Main
version: 1.0.0
api: 3.15.2
load: POSTWORLD
author: Clarence2810
description: Showing player messages below thier head

commands:
  tagmessages:
    description: Show TagMessages Commands
    aliases:
    - tm