name: TagMessages
main: Clarence2810\tagmessages\Main
version: 1.0.0
api: 3.15.0
load: POSTWORLD
author: Clarence2810
description: Showing player own messages below thier own name

commands:
  tagmessages:
    description: Show TagMessages Commands
    aliases:
    - tm
