name: TagMessages
main: Clarence2810\tagmessages\Main
version: 1.1.0
api: 3.15.0
load: POSTWORLD
author: Clarence2810
description: Showing their messages below their name

commands:
  tagmessages:
    description: TagMessages Command
    aliases:
    - tm
